#Build & Push the Docker image to Docker Hub using GitHub Actions

# Use the official Apache HTTP Server image from the Docker Hub
FROM httpd:latest

# Copy a custom 'index.html' into the Apache server's root directory for hosting
COPY ./docker-image01/index.html /usr/local/apache2/htdocs/