name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java JDK (if using Gradle for Java projects)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      # Step 3: Install Gradle
      - name: Install Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.0'  # Specify the Gradle version you use

      # Step 4: Build the project and Docker image
      - name: Build Docker image
        run: ./gradlew buildDocker

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 6: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker-image02/Dockerfile
          push: true
          tags: yagnasriv/docker-image02:latest

      # Step 7: Log out from Docker Hub (optional)
      - name: Log out from Docker Hub
        run: docker logout